---

version: "3.7"

services:
  app:
    working_dir: /app
    image: ruby:2.6.3-slim-stretch
    volumes:
      - .:/app
      - ~/bundle-install:/app/vendor/bundle # localキャッシュ用(イミフだったら外したほうがよい)
    environment:
      - TZ=Asia/Tokyo
      - BUNDLE_APP_CONFIG=/app/.bundle
